### ISSUE TITLE
CookieManager Vulnerable to "Cross-site Cooking"

### ISSUE THREAD

**Issue by ptoomey3** [nahi/httpclient#114]
The httpclient library implicitly trusts the domain returned by a Set-Cookie header when storing a cookie in the `CookieManager` for a given `HTTPClient` instance.  For example, if a `HTTPClient` is used to access `www.untrustesite.com` the following Set-Cookie response header would set the TEST_COOKIE cookie for all `.com` domains.

    Set-Cookie: TEST_COOKIE=test_value; expires=Sun, 31-Aug-2014 17:29:06 GMT; path=/; domain=.com

Once the above cookie is set, any subsequent requests made using the same `HTTPClient` instance will transmit this cookie in the request.  Moreover, a malicious site that sets the domain equal to `.` will set a cookie for any subsequent request, regardless of the domain's TLD.  This can allow a malicious site to perform various session fixation attacks.    

It appears that there is optional support to protect against some variants of this attack by setting the `netscape_rule` to `true`.  However, even with this option set it is still possible for `evilsite.com` to set a cookie for `trustedsite.com`, as the Netscape rule only tries to protect against setting overly-broad cookies (ex. `.`, `.com`, etc).  Additionally, the Netscape rule  is antiquated and is not sufficient for determining TLD values.  These issues are documented here: http://lcamtuf.blogspot.com/2010/10/http-cookies-or-how-not-to-design.html.  

In looking at other Ruby HTTP libraries I noticed that Mechanize uses the third-party library [domain_name](https://github.com/knu/ruby-domain_name) for determining whether a Set-Cookie domain is allowed based on the domain of the request (ex. a request to evilsite.com should not be able to set a cookie for the trustedsite.com domain).  I haven't fully evaluated the library, but a quick analysis of Mechanize showed that it does seem to follow expected cookie setting behavior.  

More information on Cross-site cooking can be found on Wikipedia: http://en.wikipedia.org/wiki/Cross-site_cooking.

**Comment by nahi** [comment]
#237 was merged.
