### ISSUE TITLE
POST requests can be submitted twice if the server closes a connection after the request is already sent

### ISSUE THREAD

**Issue by smarterclayton** [nahi/httpclient#142]
We are seeing duplicate POSTs sent by httpclient when a graceful restart is executed against our Apache 2.4 server, while a long running server response is being generated.

General steps:
1) Perform a post via httpclient to Apache server with keepalive enabed
2) Apache server hands off in this case to a ruby backend which takes tens of seconds to create a response
3) A graceful restart is executed against the Apache server, apache waits for #2 to complete
4) The backend server responds with a valid request, which apache sends to httpclient
5) Apache terminates the keepalive connection, which then causes ECONNRESET (I think) to be raised from the socket
6) httpclient raises KeepAliveDisconnected, catches it in protect_keep_alive_disconnected, invalidates the session, but then yields again
7) do_get_block sends a second POST to the server

Digging into the code....

https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L619 catches interrupted connection exceptions and raises KeepAliveDisconnected (judging by commits the intent of the exception is to allow higher level code to invalidate the connection from the pool).

However, the higher level code in question protect_keep_alive_disconnected yields once (which starts a request), then catches this exception.  It invalidates the session, then attempts to yield again.  If the bits however have gone out on the wire the server may have received a partial or even complete request.  If the request was a POST, this is a violation of standard client behavior (don't retry POSTs).  This _seems_ like a mismatch in intent between the lower level (notify of disconnect) and the higher level (retry the request on any disconnect)

What is the impact of removing the second yield, or only invoking it on idempotent blocks?  We were seeing a deadlock when we removed it from local code but we hadn't dug into it.  Retrying the idempotent methods makes sense, but I would expect to see non-idempotent requests raise a disconnect exception unless retry was specified.  Or am I missing something?

**Comment by sluukkonen** [comment]
The fix for this issue was reverted in 44eaa71668119d277029649cc864f4cff59d5d35. Any reasons for that? I found this issue since I'm seeing duplicate POST requests with httpclient 2.6.0.1.

**Comment by jessebs** [comment]
This is still an issue

**Comment by maxrosecollins** [comment]
I think this is still an issue, all of my post requests are sent 2x
