### ISSUE TITLE
SSL request failing on (what I believe is) a correctly configured cert

### ISSUE THREAD

**Issue by konklone** [nahi/httpclient#182]
But it does work with `Net::HTTP`. I've read through #79 and I don't believe I'm suffering the same problem.

Domain in question: [https://konklone.com](https://konklone.com)<br/>

I'm using a Class 1 (free, individual) certificate from StartSSL. It's configured as I documented in my blog post, [Switch to HTTPS Now, for Free](https://konklone.com/post/switch-to-https-now-for-free).

When I use a certificate chain including only my cert and StartSSL's [intermediate cert](http://www.startssl.com/certs/sub.class1.server.ca.pem):

```
irb(main):003:0> HTTPClient.get("https://konklone.com")
at depth 1 - 20: unable to get local issuer certificate
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

When I use a certificate chain including my cert, StartSSL's [intermediate cert](http://www.startssl.com/certs/sub.class1.server.ca.pem), and StartSSL's [root cert](http://www.startssl.com/certs/ca.pem):

```
irb(main):004:0> HTTPClient.get("https://konklone.com")
at depth 2 - 19: self signed certificate in certificate chain
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

But when I do this in `Net::HTTP`, it works.I get the same behavior regardless of whether I'm using the full certificate chain or not:

```
>> uri = URI.parse("https://konklone.com")
=> #<URI::HTTPS:0x007f4d2ff27bb8 URL:https://konklone.com>
>> http = Net::HTTP.new(uri.host, uri.port)
=> #<Net::HTTP konklone.com:443 open=false>
>> http.use_ssl = true
=> true
>> http.verify_mode = OpenSSL::SSL::VERIFY_PEER
=> 1
>> response = http.request_get('/')
=> #<Net::HTTPOK 200 OK readbody=true>
>> response.body
[the body of the page]
```

**Comment by dinvlad** [comment]
This came up for us as well - is there any way to put our self-signed cert into the trust chain _without_ using `set_trust_ca` explicitly, since our `HTTPClient` object is instantiated by a third-party library (which we have no control over)? Thanks!
