### ISSUE TITLE
HTTPClient::KeepAliveDisconnected: HTTPClient::KeepAliveDisconnected on httpclient-2.3.4.1

### ISSUE THREAD

**Issue by jigishmehta86** [nahi/httpclient#185]
HTTPClient::KeepAliveDisconnected: HTTPClient::KeepAliveDisconnected

Stack trace:
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/httpclient-2.3.4.1/lib/httpclient/session.rb:882:in `block in parse_header'
/Users/build/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/timeout.rb:69:in`timeout'
/Users/build/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/httpclient-2.3.4.1/lib/httpclient/session.rb:875:in`parse_header'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/httpclient-2.3.4.1/lib/httpclient/session.rb:858:in `read_header'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/httpclient-2.3.4.1/lib/httpclient/session.rb:667:in`get_header'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/httpclient-2.3.4.1/lib/httpclient.rb:1137:in `do_get_header'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/httpclient-2.3.4.1/lib/httpclient.rb:1086:in`do_get_block'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/httpclient-2.3.4.1/lib/httpclient.rb:887:in `block in do_request'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/httpclient-2.3.4.1/lib/httpclient.rb:986:in`rescue in protect_keep_alive_disconnected'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/httpclient-2.3.4.1/lib/httpclient.rb:980:in `protect_keep_alive_disconnected'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/httpclient-2.3.4.1/lib/httpclient.rb:886:in`do_request'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/httpclient-2.3.4.1/lib/httpclient.rb:774:in `request'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/httpclient-2.3.4.1/lib/httpclient.rb:684:in`post'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/calabash-android-0.4.9/lib/calabash-android/operations.rb:333:in `make_http_request'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/calabash-android-0.4.9/lib/calabash-android/operations.rb:293:in`http'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/calabash-android-0.4.9/lib/calabash-android/operations.rb:268:in `block in perform_action'
/Users/build/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/timeout.rb:69:in`timeout'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/calabash-android-0.4.9/lib/calabash-android/operations.rb:266:in `perform_action'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/calabash-android-0.4.9/lib/calabash-android/operations.rb:51:in`performAction'
step_definitions/user_steps.rb:39:in `block in <top (required)>'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/core_ext/instance_exec.rb:48:in`instance_exec'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/core_ext/instance_exec.rb:48:in `block in cucumber_instance_exec'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/core_ext/instance_exec.rb:69:in`cucumber_run_with_backtrace_filtering'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/core_ext/instance_exec.rb:36:in `cucumber_instance_exec'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/rb_support/rb_step_definition.rb:97:in`invoke'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/step_match.rb:25:in `invoke'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/step_invocation.rb:60:in`invoke'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/step_invocation.rb:38:in `accept'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:106:in`block in visit_step'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:105:in`visit_step'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/outline_table.rb:138:in `block (2 levels) in accept_expand'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/step_collection.rb:49:in`each'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/step_collection.rb:49:in `each'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/outline_table.rb:137:in`block in accept_expand'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/runtime.rb:83:in `block (2 levels) in with_hooks'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/runtime.rb:99:in`before_and_after'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/runtime.rb:82:in `block in with_hooks'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/runtime/support_code.rb:120:in`call'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/runtime/support_code.rb:120:in `block (3 levels) in around'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/language_support/language_methods.rb:9:in`block in around'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/language_support/language_methods.rb:91:in `call'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/language_support/language_methods.rb:91:in`execute_around'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/language_support/language_methods.rb:8:in `around'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/runtime/support_code.rb:119:in`block (2 levels) in around'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/runtime/support_code.rb:117:in `call'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/runtime/support_code.rb:117:in`around'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/runtime.rb:94:in `around'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/runtime.rb:81:in`with_hooks'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/outline_table.rb:135:in `accept_expand'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/outline_table.rb:107:in`accept'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/outline_table.rb:25:in `block in accept'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/outline_table.rb:23:in`each'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/outline_table.rb:23:in `each_with_index'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/outline_table.rb:23:in`accept'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:90:in `block in visit_outline_table'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:170:in`broadcast'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:89:in `visit_outline_table'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/examples.rb:25:in`accept'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:80:in `block in visit_examples'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:170:in`broadcast'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:79:in `visit_examples'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/scenario_outline.rb:19:in`block in accept'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/scenario_outline.rb:18:in `each'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/scenario_outline.rb:18:in`accept'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:74:in `block in visit_examples_array'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:170:in`broadcast'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:73:in `visit_examples_array'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/scenario_outline.rb:45:in`accept'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:58:in `block in visit_feature_element'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:170:in`broadcast'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:57:in `visit_feature_element'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/feature.rb:38:in`block in accept'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/feature.rb:37:in `each'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/feature.rb:37:in`accept'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:27:in `block in visit_feature'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:170:in`broadcast'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:26:in `visit_feature'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/features.rb:28:in`block in accept'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/features.rb:17:in `each'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/features.rb:17:in`each'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/features.rb:27:in `accept'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:21:in`block in visit_features'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/ast/tree_walker.rb:20:in`visit_features'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/runtime.rb:49:in `run!'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/lib/cucumber/cli/main.rb:47:in`execute!'
/Users/build/.rvm/gems/ruby-1.9.3-p484/gems/cucumber-1.3.10/bin/cucumber:13:in `<top (required)>'
/Users/build/.rvm/gems/ruby-1.9.3-p484/bin/cucumber:23:in`load'
/Users/build/.rvm/gems/ruby-1.9.3-p484/bin/cucumber:23:in `<main>'
/Users/build/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in`eval'
/Users/build/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `<main>'
features/General_Usability/Error_Message_Review.feature:31:in`Given I am on Home screen'

**Comment by jigishmehta86** [comment]
Thank you guys for the quick turnaround.

**Comment by tmccombs** [comment]
I am still getting this error when trying to POST a 3 MB zip file over https.

I am using ruby 1.9.3p484 and httpclient 2.8.2.4.

It looks like the error that triggers the KeepAliveDisconnected error is an EPIPE that originates in openssl. 

This happens every single time I make a post request to this endpoint.

Stacktrace:
```
Error: Broken pipe
/usr/lib/ruby/1.9.1/openssl/buffering.rb:318:in `syswrite'
/usr/lib/ruby/1.9.1/openssl/buffering.rb:318:in `do_write'
/usr/lib/ruby/1.9.1/openssl/buffering.rb:336:in `write'
/var/lib/gems/1.9.1/gems/httpclient-2.8.2.4/lib/httpclient/ssl_socket.rb:92:in `<<'
/var/lib/gems/1.9.1/gems/httpclient-2.8.2.4/lib/httpclient/http.rb:510:in `dump'
/var/lib/gems/1.9.1/gems/httpclient-2.8.2.4/lib/httpclient/http.rb:962:in `dump'
/var/lib/gems/1.9.1/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:510:in `block in query'
/usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
/var/lib/gems/1.9.1/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:508:in `query'
/var/lib/gems/1.9.1/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:174:in `query'
/var/lib/gems/1.9.1/gems/httpclient-2.8.2.4/lib/httpclient.rb:1240:in `do_get_block'
/var/lib/gems/1.9.1/gems/httpclient-2.8.2.4/lib/httpclient.rb:1017:in `block in do_request'
/var/lib/gems/1.9.1/gems/httpclient-2.8.2.4/lib/httpclient.rb:1131:in `protect_keep_alive_disconnected'
/var/lib/gems/1.9.1/gems/httpclient-2.8.2.4/lib/httpclient.rb:1012:in `do_request'
/var/lib/gems/1.9.1/gems/httpclient-2.8.2.4/lib/httpclient.rb:854:in `request'
```
