### ISSUE TITLE
response header handling, possible bug?

### ISSUE THREAD

**Issue by rollator** [nahi/httpclient#242]
When I get a response header like this:
{"Server"=>"nginx", "Date"=>"Tue, 06 Jan 2015 21:10:14 GMT", "Content-Type"=>"text/html; charset=utf-8", "Transfer-Encoding"=>"chunked", "Connection"=>"keep-alive", "Set-Cookie"=>"no_remember=0; expires=Wed, 06-Jan-2016 23:10:14 GMT; Max-Age=31536000; path=/; domain=.foo.com; httponly", "X-UA-Compatible"=>"IE=edge,chrome=1"}

My httpclient object will print 'Unknown key: Max-Age = 31536000' to stdout. Is this a bug or intended behaviour? Could I somehow suppress this message?

**Comment by rollator** [comment]
Would you possibly know a temporal solution which could suppress this output?

**Comment by nahi** [comment]
Please wait for a moment, I'm going to try to reproduce this on my end.

**Comment by nahi** [comment]
I can reproduce that warning;
```ruby
% ruby -rhttpclient/cookie -e 'cm = HTTPClient::CookieManager.new; cm.parse("no_remember=0; expires=Wed, 06-Jan-2016 23:10:14 GMT; Max-Age=31536000; path=/; domain=.foo.com; httponly", URI("http://www.foo.com/")); cm.cookies'
```

And I found that old cookie implementation does not support 'Max-Age'. It's an usual Ruby's warning so you can simply ignore that, and if you want to disable all Ruby warnings you can set;
```ruby
$VERBOSE = nil
```

such as;
```ruby
% ruby -rhttpclient/webagent-cookie -e '$VERBOSE = nil; cm = HTTPClient::CookieManager.new; cm.parse("no_remember=0; expires=Wed, 06-Jan-2016 23:10:14 GMT; Max-Age=31536000; path=/; domain=.foo.com; httponly", URI("http://www.foo.com/")); cm.cookies'
```
