### ISSUE TITLE
Http Clients adds extra Accept header */ * in despite of one being present in the request

### ISSUE THREAD

**Issue by girishmanyam** [nahi/httpclient#243]
With reference to ticket : Add Accept: */* to request header #92 

I am testing Rest API  service request using net/http client and setting the Accept header value as application/xxx.v1.json whilst sending the GET request. Ruby Net/http client adds additional accept value as  */*   over the wire (example : Accept=*/*, application/***.v1+json)  and my  applications can accept header value as application/xxx.v1.json. Hence i am getting the http 406 errorCode.

Is there way to delete the default accept header value */*  on fly using Net/http client

Your help is truly appreciated.

Thanks

**Comment by nahi** [comment]
You're talking about Net::HTTP, not HTTPClient, right? :-)

With httpclient gem, you can do customize like this;
```ruby
HTTPClient.get("http://www.google.com/", :header => {"Accept" => "application/json"})
```

With Net::HTTP, you can;
```ruby
Net::HTTP.new("www.google.com", 80).get("/", {"Accept" => "application/json"})
```
