### ISSUE TITLE
Zlib::DataErrors for responses with Content-Encoding: deflate

### ISSUE THREAD

**Issue by ccurtisj** [nahi/httpclient#244]
Ruby: 2.1.5
HTTPClient: 2.6.0.1

We started noticing the following exceptions occurring quite frequently after enabling `transparent_gzip_decompression` in our app:

* Zlib::DataError: incorrect header check
* Zlib::DataError: unknown compression method

The common thread seems to be that all of the offending responses have `Content-Encoding : deflate`

Steps to reproduce:

```
client = HTTPClient.new
client.transparent_gzip_decompression = true
client.get("http://www.news-medical.net")
```

```
Zlib::DataError: incorrect header check
	from /Users/ccurtisj/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/httpclient-37da3b4e7d59/lib/httpclient/session.rb:692:in `inflate'
	from /Users/ccurtisj/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/httpclient-37da3b4e7d59/lib/httpclient/session.rb:692:in `block in get_body'
	from /Users/ccurtisj/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/httpclient-37da3b4e7d59/lib/httpclient/session.rb:960:in `read_body_length'
	from /Users/ccurtisj/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/httpclient-37da3b4e7d59/lib/httpclient/session.rb:698:in `get_body'
	from /Users/ccurtisj/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/httpclient-37da3b4e7d59/lib/httpclient.rb:1197:in `do_get_block'
...
```

Here are some other example URLs:
* http://www.stockhouse.com
* https://www.aflglobal.com/Home.aspx
* http://www.hireright.com

Any ideas would be greatly appreciated, thanks!

**Comment by nahi** [comment]
Sorry for the delay in responding. I only checked "http://www.stockhouse.com" and it worked for me, but I revisit this today and found that "http://www.news-medical.net" throws an error as you stated. Let me check...

**Comment by nahi** [comment]
Oh I realized I didn't implement deflate support. Please wait for a while...

**Comment by ccurtisj** [comment]
Amazing, thanks!
