### ISSUE TITLE
Timeout for TCPSocket not working

### ISSUE THREAD

**Issue by binaryplease** [nahi/httpclient#257]
Im using httpclient with jruby 1.7.19 in a multi-threaded application.
I have set the timeouts for my httpclient like this:
````ruby
httpclient.connect_timeout = 10
httpclient.send_timeout = 10
httpclient.receive_timeout = 10
httpclient.keep_alive_timeout = 10
httpclient.ssl_config.timeout = 10
````
but sometimes threads keep waiting at
````ruby
head = httpclient.head(url, follow_redirect: true)
````
I started backtracing the stuck threads and discovered the get stuck beacuse of line
````ruby
initial_line = @socket.gets("\n")
````
Where @socket is a TCPsocket. see https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb line 915.
Is this a bug in the httpclient gem? If so is there a workaround for getting the head? The ruby timeout module isn't thread safe so I can't wrap the call with it.
Thanks

**Comment by nahi** [comment]
As the discussion in https://github.com/nahi/httpclient/pull/258 it should be JRuby's issue. Please try to update JRuby.
