### ISSUE TITLE
CA Certificates (Trust Anchors) out of date

### ISSUE THREAD

**Issue by PaulSD** [nahi/httpclient#259]
I have a ruby program that connects to a site which recently switched to using a new cert issued by the "Entrust Root Certification Authority - G2" root cert.  This root cert is not trusted by httpclient, so the connection fails.

Could you please update the trust anchor list included with httpclient?  Thanks.

**Comment by nahi** [comment]
https://github.com/nahi/httpclient/pull/273 should solve this issue.

**Comment by nahi** [comment]
Thanks for heads-up!

**Comment by nahi** [comment]
Merged. Could you try master branch? https://github.com/nahi/httpclient/commit/e70ec73cbb45ade4551d0578a0a0643662069426
Please reopen this issue if it still doesn't work for you.
