### ISSUE TITLE
How to run get request with query, headers and follow redirect?

### ISSUE THREAD

**Issue by cheneveld** [nahi/httpclient#260]
I can't find any documentation which states how to run a get request with a query, headers and a follow_redirect.

Can anyone provide an example of doing this?

Thanks

**Comment by oakesja** [comment]
http://www.rubydoc.info/gems/httpclient/2.6.0.1/HTTPClient

**Comment by cheneveld** [comment]
There is no example of my request in those docs...  Again, a GET request with a query, headers and a follow_redirect.  But I believe I did figure it out and it looks like the following

```
http = HTTPClient.new
http.get("http://someapi.com/resource",{:some_query_key => "value"}, {:some_header_key => "value}, :follow_redirect => true)
```
