### ISSUE TITLE
request to follow SemVer/mention it in README

### ISSUE THREAD

**Issue by pravi** [nahi/httpclient#266]
Do you follow semantic versioning defined at semver.org? If yes, can you mention it in README. If not, can you consider it?

**Comment by pravi** [comment]
@nahi can you reply?

**Comment by nahi** [comment]
I'm kind-of trying to follow but I sometimes introduce "incompatible" change in MINOR version update.
* unintentional
* bug fix: ex. https://github.com/nahi/httpclient/issues/285#issuecomment-169846976
I'm not sure I'm following SemVer so I'd say httpclient will try but can't promise.

**Comment by pravi** [comment]
@nahi thanks for the reply. But this means, we cannot update httpclient easily in debian :(
