### ISSUE TITLE
HTTPS broken with ssl_version set

### ISSUE THREAD

**Issue by jackycheung51** [nahi/httpclient#277]
In 2.7.0 & 2.7.0.1, the following code fails with `Java::JavaSecurity::NoSuchAlgorithmException: #<HTTPClient::SSLConfig:0x10c67c1c> SSLContext not available` on JRuby:

```
http_client = HTTPClient.new
http_client.ssl_config.ssl_version = :TLSv1_2
http_client.get 'https://www.google.com'
```

It turned out there is a bug in the constructor of HTTPClient::SSLConfig in ruby_ssl_socket.rb line 450:
```
        ssl_version = config.to_s.gsub(/_/, '.')
```
The config is an object and `config.to_s` returns `#<HTTPClient::SSLConfig:0x10c67c1c>`. The ssl_version value generated is an incorrect SSL version.

It can be fixed by changing line 450 to
```
      ssl_version = config.ssl_version.to_s.gsub(/_/, '.')
```
In the code example above, the `ssl_version` is `:TLSv1_2` and the ssl_version value generated on 450 will be `TLSv1.2` and it is a correct SSL version.

**Comment by nahi** [comment]
You're right, it's a silly bug... #282 should solve this bug.
