### ISSUE TITLE
Set  ssl_version property Jruby 

### ISSUE THREAD

**Issue by sebastianguarin** [nahi/httpclient#283]
Jruby_ssl_socket is setting is parsing the HTTP::SSLConfig instead of parse ssl_version method

https://github.com/nahi/httpclient/blob/master/lib/httpclient/jruby_ssl_socket.rb#L450

https://github.com/nahi/httpclient/pull/282

**Comment by nahi** [comment]
https://github.com/nahi/httpclient/pull/282 is merged. Thanks!
