### ISSUE TITLE
deprecated warnings with ruby 2.3.0

### ISSUE THREAD

**Issue by kikonen** [nahi/httpclient#292]
Dumped into stdout; so somewhat nuisance

httpclient-2.7.0.1/lib/httpclient/session.rb:734:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
httpclient-2.7.0.1/lib/httpclient/session.rb:500:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
httpclient-2.7.0.1/lib/httpclient/session.rb:787:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
httpclient-2.7.0.1/lib/httpclient/session.rb:867:in `read_body_length': Object#timeout is deprecated, use Timeout.timeout instead.

**Comment by elifoster** [comment]
Already resolved. See #287. @nahi perhaps we should get a new build with this.

**Comment by nahi** [comment]
@kikonen @elifoster Sure, I'll create 2.7.1 soon.

**Comment by kikonen** [comment]
Not seeing deprecation warnings in stdout with 2.7.1 any longer

**Comment by nahi** [comment]
@kikonen Thanks!
