### ISSUE TITLE
post with query

### ISSUE THREAD

**Issue by blanchma** [nahi/httpclient#293]
I want to do a post with some params in the url without writing each of them:

response = $http.post("https://login.bigcommerce.com/oauth2/token",
                  headers: {'Content-Type' => 'application/x-www-form-urlencoded'},
                  query: {client_id: 'xxx',
                          client_secret: 'yyy',
                          code: 'zzz',
                          scope: 'store_v2_customers_read_only',
                          grant_type: 'authorization_code',
                          redirect_uri: 'https://xxx.herokuapp.com/auth',
                          context: 'stores/abc',
                    });

This doesn't include the params in the URL as querystring unless is a GET. Why? Why not support query string in a post method too?

**Comment by elifoster** [comment]
Do you mean something like [this](https://github.com/FTB-Gamepedia/MediaWiki-Butt-Ruby/blob/master/lib/mediawiki/butt.rb#L50)? Sounds like what you are asking for is possible.

**Comment by blanchma** [comment]
@elifoster more like this 
Typhoeus.post("www.example.com/posts", params: { a: "test", b: "test2"})

#=> www.example.com/posts?a=test&b=test2

**Comment by elifoster** [comment]
Forgive me for not understanding what you want, but how is that different than the code snippet I linked?

**Comment by blanchma** [comment]
@elifoster sorry I didn't get your comment. Yes, that's exactly what I want. Thanks
