### ISSUE TITLE
OpenSSL warning even though on latest version

### ISSUE THREAD

**Issue by vlerenc** [nahi/httpclient#297]
I get the warning ```RSA 1024 bit CA certificates are loaded due to old openssl compatibility``` even though I have the latest OpenSSL version installed.
``` shell
$ openssl version
OpenSSL 1.0.2f  28 Jan 2016
```

**Comment by vlerenc** [comment]
The code at https://github.com/nahi/httpclient/blob/master/lib/httpclient/ssl_config.rb#L446-L447 doesn't seem to cope with an OpenSSL version date at the end (not sure whether this has changed over time; I compiled 1.0.1p and 1.0.2f for Ubuntu and get the date for both versions).

The trouble with the warning is that it gets used by some gems which are then used by some scripts which get confused by the warning when parsing the output.

**Comment by josegrad** [comment]
Is there a way to fix this? Looks quite nasty in producction.

**Comment by runa** [comment]
I'm getting mails from CRON since I have a few rake tasks that end up printing this warning.
Would you accept a PR making the warning configurable?

**Comment by nahi** [comment]
Sorry for any troubles my "excuse" check caused... @runa yes, thank you!

**Comment by runa** [comment]
@nahi I couldn't find any kind of "global options", everything is per client instance, right?
My problem is that I'm not using the gem directly but thru another gem (google-ads-common) and I'm not sure if I can reach the `HTTPClient::SSLOptions` instance...

**Comment by nahi** [comment]
Yeah, only I can think of is ENV like for HTTP_PROXY. But it should not be easy in case where you're just using a gem which depends on httpclient. Let me try to think about it tomorrow JST. The worst case is ENV but I hope I can find another workaround.

**Comment by elifoster** [comment]
@runa You could submit a PR to google-ads-common that makes the client an attribute reader so you have access to it.

**Comment by runa** [comment]
@elifoster Yep; In fact, google-ads-common is adapter agnostic (well, more or less). I could switch to HTTPi; but I have this warning from other gems too. I'll wait for @nahi's discussion with the pillow and see :)

**Comment by nahi** [comment]
Please try 2.7.2.
