### ISSUE TITLE
Asynchronous https request to some urls never ends

### ISSUE THREAD

**Issue by bblimke** [nahi/httpclient#299]
Tested with latest version 2.7.1

This works:
````
require 'httpclient'
p HTTPClient::VERSION
c = HTTPClient.new
con = c.get_async("https://rubygems.org/")
con.join
=> nil
````

This hangs:
````
require 'httpclient'
p HTTPClient::VERSION
c = HTTPClient.new
con = c.get_async("https://rubygems.org/gems")
con.join #this hangs forever
```` 

This hangs:
````
require 'httpclient'
p HTTPClient::VERSION
c = HTTPClient.new
con = c.get_async("https://github.com")
con.join #hangs forever too
````

**Comment by elifoster** [comment]
Those all seem to work fine for me :confused:

**Comment by bblimke** [comment]
@elifoster thank you for testing that. I get this consistently, but even with older versions of httpclient. I also had the same issues on travis on different ruby versions. not sure how to figure out the reason though.

I'll close it for now. Perhaps someone will experience the same issue and add a comment.
