### ISSUE TITLE
Allow two-arg blocks with follow_redirect: true

### ISSUE THREAD

**Issue by sqrrrl** [nahi/httpclient#304]
Blocks to allow streaming responses can take either 1 or 2 parameters. If one, the response chunk is returned, if two, then both the response object and the chunk are returned.

However, if `follow_redirect: true` is used, then only 1 value is ever returned to the block, just the chunk. 

This is problematic in cases where the status code or headers needs to be checked before processing a chunk. An example of this is using a `Range` header to request partial content. A server *may* opt to return a 200 response with the full content instead of a 206 response with partial content. Without knowing the status codes, it's difficult to properly handle streaming the content (e.g. rewind output stream on 200 response, just append on 206...)

HTTPClient.follow_redirect should have similar logic to HTTPClient.request to check the # of expected args an honor the caller's preference.

**Comment by nahi** [comment]
You're correct. I'll merge #306. Thank you.
