### ISSUE TITLE
undefined method _httpclient_cert_store_items

### ISSUE THREAD

**Issue by Paxa** [nahi/httpclient#329]
Installed latest version and got this error:

```
NoMethodError: undefined method `_httpclient_cert_store_items` for #<OpenSSL::X509::Store:0x007fb79511ba80>
/Users/pavel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/httpclient-2.8.2.1/lib/httpclient/ssl_config.rb:211:in `clear_cert_store`
```

With `2.8.2` it working fine

**Comment by nahi** [comment]
@Paxa sorry, will fix soon. It broke httpclient no CRuby...

**Comment by nahi** [comment]
#330 should fix this problem. I'll push it as 2.8.2.2 after CI passes.

**Comment by nahi** [comment]
I've just pushed 2.8.2.2 to rubygems.org. Please try it at your leisure.

**Comment by Paxa** [comment]
Awesome, thanks!
