### ISSUE TITLE
Disabling SSL verification still broken in JRuby

### ISSUE THREAD

**Issue by petr666** [nahi/httpclient#331]
Hi,
fix in  #319 is insufficient. I found disabling verification still fails in case common name (or alternative names) in certificate does not match. First case fails with

Certificate for <localhost> doesn't match common name of the certificate subject: foo.com

second fails with

Certificate for <localhost> doesn't match any of the subject alternative names: ["*.foo.com"]

Again I'm attaching simple test script.
[ssl_verification_problem.txt](https://github.com/nahi/httpclient/files/424696/ssl_verification_problem.txt)

**Comment by nahi** [comment]
@petr666 Ah, sorry, I looked over your point in https://github.com/nahi/httpclient/issues/276#issuecomment-234244551. JRubySSLSocket#post_connection_check should check verification configuration like SSLSocket#post_connection_check does. Let me fix it.

**Comment by nahi** [comment]
https://github.com/nahi/httpclient/pull/332

**Comment by nahi** [comment]
I pushed 2.8.2.3 with #332. Please check 2.8.2.3 and reopen if it's still insufficient. I added your script as test case. Thank you!
