### ISSUE TITLE
SSL sessions should not be reset every request when used with Faraday

### ISSUE THREAD

**Issue by dgolombek** [nahi/httpclient#343]
This is a companion bug to lostisland/faraday#624 -- for SSL connections, Faraday currently calls ssl_config.verify_mode= and ssl_config.cert_store= before every request, which in turn call ssl_config.change_notify and reset all open sessions. This is mostly a Faraday bug in usage but it'd make sense to have all of the ssl_config setters only call change_notify if the value is actually changed. This would make it easier for Faraday to avoid this problem.

The check on several of these will be object equality rather than proper ruby equivalence checks, given that they are OpenSSL C Structs, but that at least gives the caller a way to avoid the reset by passing the same object in each time.

**Comment by nahi** [comment]
Thanks. Agree with you that it's a problem of SSLConfig. I merged #344 and modified a little at #347. Let me know other problems with Faraday if any.
