### ISSUE TITLE
Dependency Problem

### ISSUE THREAD

**Issue by BrackXs** [nahi/httpclient#360]
The use of RUBY_ENGINE (in session.rb) disables usage with MRI-Ruby 1.8.7 since this constant was introduced with ruby 1.9.

if defined? RUBY_ENGINE && RUBY_ENGINE == 'jruby'
in line 24 of session.rb solves this problem.
Otherwise you should declare a dependency on ruby 1.9+

**Comment by nahi** [comment]
@BrackXs Thanks, I didn't know I broke 1.8 compatibility. But it became difficult to keep test cases green on 1.8 so I removed CRuby 1.8 and CRuby 1.9 support at a531919591b7b2568d70b4d19c33793346968287. This time I tried to modify code a little to support 1.8, but SSL incompatibility was hard to fix.
As .travs.yml says current supported version is from 2.0.

**Comment by nahi** [comment]
I found https://github.com/nahi/httpclient/pull/358 and now merged. Please check whether it solves your problem or not.
