### ISSUE TITLE
SocketError: getaddrinfo: Temporary failure in name resolution (2.8.3)

### ISSUE THREAD

**Issue by tit** [nahi/httpclient#408]
I'm making about a hundred consecutive HTTP requests via HTTPClient.

```ruby
['https://example.com', ..., 'https://example.org'].each do |url|
response = HTTPClient.get url
```

Sometimes get error: `SocketError: getaddrinfo: Temporary failure in name resolution.`

What I do wrong?

My system:
1. Ubuntu 18.10
2. ruby 2.5.1
3. httpclient (2.8.3)

**Comment by ronan-mch** [comment]
This is probably not related to this library, `[getaddrinfo](http://man7.org/linux/man-pages/man3/getaddrinfo.3.html)` is the system call that does DNS resolution. A temporary failure in name resolution indicates that the DNS server is not available right now. There could be multiple reasons for this, depending on how DNS resolution works in your environnment.

**Comment by tit** [comment]
thanx!
