### ISSUE TITLE
receive timeout error

### ISSUE THREAD

**Issue by yagmurdursun** [nahi/httpclient#86]
hi, I am using Httpclient gem for user signup. While my sign up controller working I get "HTTP Client::ReceiveTimeout Error in User Controller#signupexecution expired." I think if I set receiveTimeout the problem will be solved. I googled and couldn't find any solution. How can I solve the problem?

**Comment by hickscorp** [comment]
This issue is starting to pop a bit everywhere around. I'm suspecting a much lower level issue with a deadlock maybe. Did anyone get that sorted?

**Comment by megpolo3** [comment]
@yagmurdursun @hickscorp Did anyone find any solution. This issues is causing me problem now.

**Comment by hickscorp** [comment]
@megpolo3 Unfortunately no. We ended up changing the HTTP client.
